google/leveldb

- README.md
This replaces htmlpreview with [rawgit](http://rawgit.com/).
rawgit is faster and doesnt use JS to render the page, making it SEO friendly.
> readme: improved documentation link

- port/atomic_pointer.h
port/atomic_pointer.h was missing an implementation for
MemoryBarrier() for this platform.
Fixes #115.
> Fix Android/MIPS build.

- db/db_impl.cc
The `FinishCompactionOutputFile()` method write a log like this:
```
Generated table #132: 803288 keys, 21119441 bytes
```
The level of the output file is missing, I change it to write log message like this:
```
Generated table #132@1: 803288 keys, 21119441 bytes
```
Which is similar to other logs, like
```
Compacted 1@1 + 1@2 files => 17115883 bytes
```
> log compaction output file's level along with number

- util/env_boost.cc
boost::interprocess::file_lock: lock -> try_lock, it corresponds to method Env::FileLock specification.
> [PosixEnv::FileLock] fix

- db/skiplist_test.cc
This fixes a signed/unsigned mismatch on Windows/VC++ builds with VC++ 2013 and 2015. It happens when we do a 64-bit build of leveldb_skiplist_test, with this command:
ninja -C out\Release_x64 leveldb_skiplist_test
The warning is:
third_party\leveldatabase\src\db\skiplist_test.cc(252): warning C4018: '>': signed/unsigned mismatch
I am a Google employee and therefore approved for submitting PRs to this repo.
> Fix signed/unsigned mismatch on VC++ builds

- db/recovery_test.cc
-This fixes compile errors with default setup on RHEL 6 systems.
> Change std::uint64_t to uint64_t

- CMakeLists.txt
- db/version_set.cc
- db/version_set_test.cc
- issues/issue320_test.cc
Closes google/leveldb#320
During compaction it was possible that records from a block b1=(l1,u1)
would be pushed down from level i to level i+1. If there is a block
b2=(l2,u2) at level i with k1 = user_key(u1) = user_key(l2) then
a subsequent search for k1 will yield the record l2 which has a smaller
sequence number than u1 because the sort order for records sorts
increasing by user key but decreaing by sequence number.
This change add a call to a new function AddBoundaryInputs to
SetupOtherInputs. AddBoundaryInputs searches for a block b2 matching the
criteria above and adds it to the set of files to be compacted. Whenever
AddBoundaryInputs is called it is important that the compaction fileset
in level i+1 (known as c->inputs_[1] in the code) be recomputed. Each
call to AddBoundaryInputs …
> Fix snapshot compaction bug

- db/db_iter.cc
When iter_ is pointing to current key, we can safely move to the next
key to avoid checking current key, which is of course not necessary.
Benchmark shows that 'readseq' has about 8% performance improvement.
Without patch:
>./db_bench --benchmarks=readseq --num=$((4<<20)) --db=/tmp/db --use_existing_db=1
LevelDB:    version 1.21
Date:       Thu Apr 25 09:37:21 2019
CPU:        32 * Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
CPUCache:   20480 KB
Keys:       16 bytes each
Values:     100 bytes each (50 bytes after compression)
Entries:    4194304
RawSize:    464.0 MB (estimated)
FileSize:   264.0 MB (estimated)
------------------------------------------------
readseq      :       0.196 micros/op;  565.7 MB/s
With patch:
>./db_bench --benchmarks=readseq --num=$((4<<20)) --db=/tmp/db …
> don't check current key in DBIter::Next()

- CMakeLists.txt
- port/port_config.h.in
- util/env_posix.cc
- util/env_posix_test.cc
This prevents file descriptors from leaking to child processes.
When compiled for older (pre-2.6.23) kernels which lack support for `O_CLOEXEC`, there is no change in behavior.  With newer kernels, child processes will no longer inherit leveldb's file handles, which reduces the changes of accidentally corrupting the database.
Fixes #623
> Add O_CLOEXEC to open calls.

- db/dbformat.h
- db/version_edit.cc
```
Program received signal SIGABRT, Aborted.
__libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
44      ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
#1  0xb6e11ebe in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xb6e14716 in __GI_abort () at abort.c:89
#3  0xb6e0d104 in __assert_fail_base (fmt=0x1 <error: Cannot access memory at address 0x1>, assertion=0x63210 "!rep_.empty()", assertion@entry=0x0,
file=0x63220 "./db/dbformat.h", file@entry=0xb6ff9000 "", line=171, line@entry=3068948644,
function=function@entry=0x634b8 <leveldb::InternalKey::Encode() const::__PRETTY_FUNCTION__> "leveldb::Slice …
```
> broken db: fix assertion in leveldb::InternalKey::Encode, mark base as corrupt

- db/version_set.cc
This code has been tested with existing tests and no new tests are written because it justs implements  Version:: Get() with Version:: ForEachOverlapping() which has been fully tested.
> Use Version::ForEachOverlapping to implement Version::Get()

- table/table.cc
In Table::Open function, we already judge status just after Decode footer, so the status judge before read index block is duplicate and unnessary,  we can remove it.
> Remove unnecessary status check

- db/builder.cc
During the compaction phase, in this function
```
Status DBImpl::WriteLevel0Table(MemTable* mem, VersionEdit* edit,
Version* base)
```
It will then call
```
BuildTable(const std::string& dbname, Env* env, const Options& options,
TableCache* table_cache, Iterator* iter, FileMetaData* meta)
```
In BuildTable function, the code fragment is this:
```
TableBuilder* builder = new TableBuilder(options, file);
meta->smallest.DecodeFrom(iter->key());
for (; iter->Valid(); iter->Next()) {
Slice key = iter->key();
meta->largest.DecodeFrom(key);
builder->Add(key, iter->value());
}
```
In the iterator loop, call meta->largest.DecodeFrom(key)  every time is unnecessary, which will copy every key to meta's largest field. We just need to copy the last key after the iteration is done.
```
bool …
```
> avoid unnecessary memory copy

- db/db_test.cc
A recent change (ed78107) switched from `%8d` to `%8zu` for fprintf'ing a uint64_t value which does not work on all platforms. This should fix platforms by using the PRIu64 constant.
> Fixed fprintf of 64-bit value.

- .gitmodules
- CMakeLists.txt
Recent changes (ed78107 and 99ab473) introduced the use of the google/benchmark library. This change adds the necessary Git submodule and cmake changes to successfully build.
> Added google/benchmark submodule.

- include/leveldb/c.h
This fixes a build failure in an upcoming version of the Apple toolchain.
More details at https://github.com/firebase/firebase-ios-sdk/pull/7563
> Don't include C++ headers in extern C

- util/env_posix.cc
Since https://github.com/google/leveldb/commit/d177a026, pthreads is not used directly and leveldb relies on the C++11 threading primitives.
> Remove <pthread.h> include

- util/env_windows.cc
I recently encountered a problem with this because Windows doesn't allow
files to be deleted when there's open handles to them.
Other files opened by leveldb are not affected because by and large they
are using CreateFileA, which does not allow inheritance when
lpSecurityAttributes is null (ref:
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea)
However, fopen() _does_ allow inheritance, and it needs to be expressly
disabled.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-160
> Windows: Prevent LOG handle from being inherited by subprocesses

- include/leveldb/cache.h
Since https://github.com/google/leveldb/commit/e3584f9c28833ec0530b39540ffd406ee41dbc3a the `LRUCache` doesn't inherit from `Cache` anymore. It's replaced by `ShardedLRUCache`.
The codes in `cache.h` is no longer used. This PR deletes them.
> remove useless code in cache.h

- util/env_posix.cc
`std::memory_order::memory_order_relaxed` is removed since C++ 20: https://en.cppreference.com/w/cpp/atomic/memory_order. 
Running `cmake -DCMAKE_CXX_STANDARD=20 .. && cmake --build .` gives the following error:
```
leveldb/util/env_posix.cc:890:35: error: no member named 'memory_order_relaxed' in 'std::memory_order'; did you mean 'std::memory_order_relaxed'?
assert(!env_initialized_.load(std::memory_order::memory_order_relaxed));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
std::memory_order_relaxed
```
This PR fixed this issue.
> `std::memory_order::memory_order_relaxed` -> `std::memory_order_relaxed`

- db/skiplist.h
There are already existing functions in [random.h](https://github.com/google/leveldb/blob/5d94ad4d95c09d3ac203ddaf9922e55e730706a8/util/random.h#L53), but the original expression is still used [here](https://github.com/google/leveldb/blob/5d94ad4d95c09d3ac203ddaf9922e55e730706a8/db/skiplist.h#L246)
> Replace "(Random::Next() % kBranching) == 0" with "Random::OneIn(kBranching)"  

- util/env_posix_test.cc
```
// Exhaust the RandomAccessFile mmap limit. This way, the test
// RandomAccessFile instance below is backed by a file descriptor, not by an
// mmap region.
leveldb::RandomAccessFile* mmapped_files[kReadOnlyFileLimit] = {nullptr};
for (int i = 0; i < kReadOnlyFileLimit; i++) {
ASSERT_LEVELDB_OK(env_->NewRandomAccessFile(file_path, &mmapped_files[i]));
}
```
In above code; we should use kMMapLimit to exhaust the RandomAccessFile mmap;
Otherwise when kMMapLimit is not equals to kReadOnlyFileLimit, this test would failed
> Fixed incorrect limit in env_posix_test.cc

- db/log_reader.h
In accordance with issue #878, I have rectified  `log_reader.h` [Line 27](https://github.com/google/leveldb/blob/1998c0ef15f0fb64994e165230473337f041fd8c/db/log_reader.h#L27).
> Fix log_reader.h documentation error

- util/cache.cc
LRUHandle has no member "next_", fix it to "next" instead.
> Fix typo in comment of LRUHandle

- db/skiplist.h
already include the header file `arena.h`, delete forward declaration for `class Arena`
https://github.com/google/leveldb/blob/f57513a1d6c99636fc5b710150d0b93713af4e43/db/skiplist.h#L34-L39
> Delete an unnecessary forward declaration

- include/leveldb/options.h
Structs with user-declared constructors are no longer considered
aggregates.  Just remove the constructor declaration where applicable.
Bug: chromium:1284275
> Fixes for C++20 support.

- util/env_test.cc
As allowed by the documentation for Env::Schedule(), ChromiumEnv may execute functions on multiple threads and guarantees no sequencing. EnvTest.RunMany assumed that functions ran in order, is the case for the stock PosixEnv and WindowsEnv implementations. This change updates the test to not assume sequential execution.
> Fix EnvTest.RunMany to allow parallel execution

- db/db_test.cc
- db/recovery_test.cc
- util/env_test.cc
There are a couple differences between ChromiumEnv and PosixEnv/WindowsEnv which cause test failures that are fixed (or at least patched over) in this change:
* NewSequentialFile() and NewRandomAccessFile() return Status::IOError rather than Status::NotFound when a file is not found, due to https://crbug.com/760362. This means a few tests need to expect a different error result.
* GetChildren() never returns the '.' or '..' entries.
> Fix tests when run against ChromiumEnv

- include/leveldb/slice.h
This allows this type to meet the requirements of e.g. std::ranges::range, which is necessary for it to work with the std::span range constructor, or the "non-legacy" constructor for Chromium's base::span.
Bug: none
> [jumbo] Add begin()/end() to Slice.

- util/hash.cc
It is UB to exceed the bounds of the buffer when doing pointer arithemetic. That means the following is not a valid bounds check:
if (start + 4 <= limit)
Because if we were at the end of the buffer, we wouldn't be allowed to add 4 anyway. Instead, this must be written as:
if (limit - start >= 4)
Basic forms of this issue are flagged by UBSan. If building with -fsanitize=undefined, the following test trips an error:
[ RUN      ] HASH.SignedUnsignedIssue
.../leveldb/util/hash.cc:30:15: runtime error: applying non-zero offset 4 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/local/google/home/davidben/leveldb/util/hash.cc:30:15 in
[       OK ] HASH.SignedUnsignedIssue (1 ms)
> Fix invalid pointer arithmetic in Hash

- include/leveldb/slice.h
- util/hash.cc
These changes
1) 2cc36eb - "[jumbo] Add begin()/end() to Slice."
2) 578eeb7 - "Fix invalid pointer arithmetic in Hash (#1222)"
were committed in the public repository but never got imported to the internal Google repository.
Later, cl/713346733 landed in the internal repo. When tooling published the internal change as 302786e ("Fix C++23 compilation errors in leveldb"), it accidentally reverted commits (1) and (2).
This change re-commits a bundled version of (1) and (2) in the public repo. This will then be imported to the private repo, leaving the 2 in sync.
> Reland changes accidentally reverted in 302786e
